### ISSUE TITLE
UnboundLocalError: local variable 'skip_idx' referenced before assignment

### ISSUE THREAD

**Issue by StrangeTcy** [EleutherAI/gpt-neo#145]
**Describe the bug**
UnboundLocalError: local variable 'skip_idx' referenced before assignment

**To Reproduce**
1. Trying running the example notebook in Colab
2. Get to the training part (where `main.py` is called)
3. Run into the error that ends in:
```
File "/content/GPTNeo/inputs.py", line 346, in sequential_input
    skip_idx, remainder = _get_skip_index(filenames, n_batches=global_step * params["train_batch_size"]) # TODO: fix for > 1 epoch
  File "/content/GPTNeo/inputs.py", line 295, in _get_skip_index
    return skip_idx, remainder
UnboundLocalError: local variable 'skip_idx' referenced before assignment
```

**Expected behavior**
Clean training on TPUs

**Proposed solution**
As I understand it, adding a line like `count = 0` to [`inputs.py`](https://github.com/EleutherAI/gpt-neo/blob/master/inputs.py), line 279 should solve the problem.

**Comment by StellaAthena** [comment]
Hi! Thanks for the feedback. We pushed some updates including a totally revamped notebook, give it a try and let me know if you're still getting this error.

**Comment by JanPokorny** [comment]
@StrangeTcy I got this error when I wrongly specified the dataset path in the JSON in "Tokenize and Upload Data" section (it saved to a folder called "Custom" instead of my dataset name).

@StellaAthena This happened to me with the current version. But it was only a matter of an "unfriendly error message" since the _real_ problem was that the set of files was empty.
