### ISSUE TITLE
[help] Does it require CUDA 10.x or can it run on CUDA 11.x

### ISSUE THREAD

**Issue by yangliu2** [EleutherAI/gpt-neo#211]
**Describe the bug**
When running `main.py` will the instruction in readme, 
log complaint that I don't have "libcusolver.so.10". So I wasn wondering if it looks specifically for CUDA 10.x
'save_config' require google cloud crediential. Do I have to use google cloud, or can I use GPU locally?

**Comment by mallorbc** [comment]
I can confirm that I have run the 2.7B parameter model on my RTX 3090.  It takes some bug fixing of the code, but it works with CUDA 11.  I will go over it more later.

**Comment by BiaChaudhry** [comment]
Hi, @mallorbc I would like to know the system requirements to run GPTneo 1.3B with minimum response time, do you have any idea?

**Comment by mallorbc** [comment]
I forgot about this.  The bug in this code has to do with the fact that this was trained with TPUs in mind rather than GPUs.  Thus, there are configurations in the x y for mesh tensorflow that need to be changed.  These x y values correspond to how the model is split and how the data is split.  I have this fixed myself, but I don't think it has been fixed on master.  I need to get time to clean it up and make a pull request.

**Comment by mallorbc** [comment]
@BiaChaudhry I do not know specific details to answer your question.  I have ran the 2.7B parameter model, but I have not tuned it.  I have not ran the 1.3B paramter model at all, but the requirements will be less. For the 2.7B model it took over 16GB of vram, I think it was 18 but I don't recall for sure.  I personally I have a 6 core ryzen 3600, 64 GB of RAM and a 3090.  Only the 3090(or server GPUS) is a hard requirement though, or several lower end GPUs to spread the model over.  The other components likely could be reduced.
