### ISSUE TITLE
Colab: Download of pre trained dataset not possible. the-eye.eu is offline

### ISSUE THREAD

**Issue by JonasPertschy** [EleutherAI/gpt-neo#261]
**Descriptions**
It is currently not possible to access any dataset or pretrained model. the-eye.eu is not accessible. Also the alternative host "eaidata.bmk.sh" does not serve the data. This makes the Google Colab workbook not operational and prevents me from realizing my usecase.

**To Reproduce**
Try to open one of the following two links:

- https://the-eye.eu/public/AI/gptneo-release/GPT3_XL/
- http://eaidata.bmk.sh/data/gptneo-release/GPT3_XL/

**Expected behavior**
Status Code 200 ("Resource found").

**Proposed solution**
Provide an alternative mirror for the files.

Affected file: GPTNeo_example_notebook.ipynb

**Comment by StellaAthena** [comment]
The eye is currently offline due to a natural disaster. They are working to get back online and we are working with them and other partners to establish additional hosts for our datasets so that service isn't interrupted in the future.

The models you are specifically looking for are currently available [on HuggingFace](https://huggingface.co/EleutherAI/gpt-neo-1.3B).
