### ISSUE TITLE
GPT3_1_3B configuration for a v3-32 TPU

### ISSUE THREAD

**Issue by iliemihai** [EleutherAI/gpt-neo#262]
Hi,

Thank you for releasing the training code for GPT-NEO. We want to train a new model from  scratch using own vocabulary and corpus.

 Due to time constraints and resources we want to train a 1.3 billion parameters (GPT_1.3B) model.

We are not sure which config suits best our needs https://github.com/EleutherAI/gpt-neo/tree/master/configs  or if we have to modify an existing config for training the 1.3B parameters model.

**Comment by StellaAthena** [comment]
The [XL Config](https://github.com/EleutherAI/gpt-neo/blob/master/configs/gpt3_XL_256_Pile.json) is a 1.3B parameter model. The naming scheme is admittedly confusing, but chosen to be consistent with [GPT-3's](https://arxiv.org/abs/2005.14165). I regularly consult Table 2.1 from that paper as a cheat sheet:

![Capture](https://user-images.githubusercontent.com/15899312/146950436-860eb632-673d-4944-832e-aad9c1a51fa4.PNG)

Note that you will likely need to modify some arguments such as `train_batch_size` and `train_steps` based on your dataset and `mesh_shape` and `layout` based on your hardware. These values for mesh shape and layout are for a v3-256 TPU.

If you are interested in training on GPUs instead of TPUs, I recommend using [our recent GPU codebase](https://github.com/EleutherAI/gpt-neox) instead. We haven't released any models trained using it yet, but it's been highly performant in internal testing and we hope to release some models soon.

**Comment by iliemihai** [comment]
Thank you for the quick response :). We have a 32 TPUv3 server,that s the reason why we use gpt_neo not gpt_neox.

**Comment by StellaAthena** [comment]
Gotcha! I haven't experimented with a v3-32 in over a year at this point, but I think we found that a `N x 2` mesh is generally the most effective. That said, there's only a handful of combinations for you to check so I would run them all for a couple hours and see what gets the best performance.

Best of luck with training your models!
