### ISSUE TITLE
LAMBADA metric_fn inaccurate for multi-token responses

### ISSUE THREAD

**Issue by sdtblck** [EleutherAI/gpt-neo#75]
we need to check if the answer is split across multiple tokens rather than just calculating accuracy from the very last token. 

should just be able to parse whether the token has a space at the beginning of the word and if not, take the previous token as well.

https://github.com/EleutherAI/GPTNeo/blob/master/model_fns.py#L255

**Comment by kevinwatkins** [comment]
My understanding was that that was how OpenAI had done it (last token rather than all the tokens of the last word), based on this remark at https://github.com/openai/gpt-2/issues/131#issuecomment-497136199. But of course that could be my misinterpretation, or you might not want to follow them in that; it does seem rather odd.

> Simplifying the procedure to test accuracy by comparing for equality of last BPE token instead of last word the accuracy is up to 46.89

**Comment by sdtblck** [comment]
Hm, we had "WutheFwasthat" from OpenAI from the discord in our server the other day, and he seemed to concur with my statement above. I think the other guy in that thread is not OpenAI affiliated.

**Comment by kevinwatkins** [comment]
Cool... I should catch up with the Discord, sorry about that

**Comment by leogao2** [comment]
We probably want this fixed asap so we can run LAMBADA on the Pile ablation

**Comment by StellaAthena** [comment]
@leogao2 @sdtblck Is this still a concern?
